### ISSUE TITLE
Needs Documentation for Build

### ISSUE THREAD

**Issue by JonathanHWood** [JolokHD/FractalClock#1]
This looks like a great project, and I'd love to try to get it to run on my phone. However, I have no clue how to build it into an apk or some other format that I can upload and let run.

Could you create some documentation demonstrating how to build, upload, and run the code?
Thanks!

**Comment by JannesAlthoff** [comment]
You can open this in Android Studio click Gradle Sync and click on Compile or you could Download one of the Releases

**Comment by JannesAlthoff** [comment]
Now Documented in Readme
